# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  push:
  repository_dispatch:

jobs:
  validate:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@next
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          # https://github.com/cloudflare/wrangler-action/issues/17#issuecomment-581472647
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
